apiVersion: v1
# Adevertisement for diff volume options that are available
kind: PersistentVolumeClaim
metadata: 
  name: database-persistent-volume-claim
spec:
  accessModes:
    # Multiple nodes can read from this PV - Persistent Volume at the same time 
    # - ReadOnlyMany
    # Only single node can read and write from this PV at the same time 
    - ReadWriteOnce
    # Multiple nodes can read and write from this PV at the same time 
    # - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  